name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependency
        run: git clone https://github.com/kana/vim-textobj-user.git $GITHUB_WORKSPACE/vim-textobj-user

      # Runs a single command using the runners shell
      - name: Run test_select.vim
        run: |
          vim --clean -S test/run_test.vim test/tests/test_select.vim || (vim_exit_code=$?; cat $GITHUB_WORKSPACE/test/tests/test_select.vim.failed.log; exit $vim_exit_code)

      # Runs a set of commands using the runners shell
      - name: Run test_move.vim
        run: |
          vim --clean -S test/run_test.vim test/tests/test_move.vim || (vim_exit_code=$?; cat $GITHUB_WORKSPACE/test/tests/test_move.vim.failed.log; exit $vim_exit_code)